version: '3.8'

services:
  flask:
    build: ./app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
      - mongo-init

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-init:
    image: mongo
    depends_on:
      - mongo
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    entrypoint: [ "mongo", "--host", "mongo", "/docker-entrypoint-initdb.d/init.js" ]

volumes:
  mongo-data:
