version: '3.8'

services:
  flask:
    build:
      context: .  # The build context is the current directory (root of the project)
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    deploy:
      replicas: 3
      placement:
        constraints: [ node.role == worker ]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init:/docker-entrypoint-initdb.d

volumes:
  mongo-data: