version: '3.8'

services:
  flask:
    build:
      context: .  # The build context is the current directory (root of the project)
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
      - mongo-init

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-init:
    image: mongo:latest
    depends_on:
      - mongo
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    entrypoint: [ "mongosh", "--host", "mongo", "/docker-entrypoint-initdb.d/init.js" ]

volumes:
  mongo-data:
