version: '3.8'

services:
  flask:
    image: tunaxx/flask-app:latest  # Use the pre-built image
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    deploy:
      replicas: 2  # Number of replicas for Flask service
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints: [node.role == worker]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure



volumes:
  mongo-data:
    driver: local

networks:
  flask-app_default:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.0.5.0/24
