name: Security SAST and DAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Install dependencies
        run: |
          pip install -r requirements.txt && pip install pytest-json

      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings --exitfirst -v --junitxml=pytest_report.xml --json=pytest_report.json || true

      - name: Install Bandit
        run: |
          pip install bandit

      - name: Run Bandit scan
        run: |
          bandit -r . -v -o bandit-report.json || true

      # Install dependencies
      - name: Install OWASP ZAP
        run: |
          # Update package list
          sudo apt-get update
          
          # Download OWASP ZAP .deb package
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Ubuntu_18.04.deb
          
          # Install the downloaded .deb package
          sudo dpkg -i ZAP_2.11.1_Ubuntu_18.04.deb
          
          # Install any missing dependencies
          sudo apt-get install -f

      - name: Run OWASP ZAP scan
        run: |
          zap-baseline.py -t http://164.92.84.183:5000/ -g gen.conf -r zap_report.html || true

# Upload Bandit Report as Artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: bandit-report
          path: bandit_report.json

      - name: Pytest
        uses: actions/upload-artifact@v4.6.2
        with:
          name: pytest_report.json
          path: pytest_report.json

      - name: Owasp
        uses: actions/upload-artifact@v4.6.2
        with:
          name: zap_report.html
          path: zap_report.html
