name: Security SAST and DAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Install dependencies
        run: |
          pip install -r requirements.txt && pip install pytest-json

      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings --exitfirst -v --junitxml=pytest_report.xml --json=pytest_report.json || true

      - name: Install Bandit
        run: |
          pip install bandit

      - name: Run Bandit scan
        run: |
          bandit -r . -v -o bandit_output.json || true

      # Install dependencies
      - name: Install OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get install -y zaproxy

      - name: Run OWASP ZAP scan
        run: |
          zap-baseline.py -t http://164.92.84.183:5000/ -g gen.conf -r zap_report.html || true

